export const initialCalculationData = {
  lengthOfReel: 0,
  widthOfReel: 0,
  weightOfColumn: 0,
  numberOfColumns: 0,
  numberOfReels: 0,
  weightOfRoll: 0,
  weightOfCore: 0,
  priceOfAdhesive: 0,
  priceOfCore: 0,
  costOfCarton: 0,
  costOfShrink: 0,
  costOfWorkmanship: 0,
  costOfTransportation: 0,
};
